seed: 42
device: auto

data:
  root: ./data
  img_size: 224
  num_classes: 7
  class_names: [anger, disgust, fear, happy, neutral, panic, sadness]

train:
  model_name: efficientnet_b0
  use_pretrained: true
  freeze_backbone: false
  batch_size: 128
  epochs: 35
  optimizer: adamw
  lr: 5.0e-4
  weight_decay: 2.0e-4
  amp: auto
  scheduler: cosine
  num_workers: 8

loss:
  type: cb_focal # ce_ls | focal | cb_focal | logit_adjusted
  label_smoothing: 0.0
  focal_gamma: 2.0
  cb_beta: 0.9999
  la_tau: 1.0

eval:
  metric: macro_f1
  save_best_by: macro_f1

save:
  run_dir: runs/250814_1600
  best_name: best.pt

log:
  interval: 50
